/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema_los_amigos.Formularios.formEmpleados;

import sistema_los_amigos.Formularios.formAdmin.*;

/**
 *
 * @author esmer
 */
public class menuPrincipalEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipalEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_inicioSesión = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_Activaciones = new javax.swing.JLabel();
        lbl_bienvenida = new javax.swing.JLabel();
        btn_registrarVentas = new javax.swing.JButton();
        btn_cerrarSesion = new javax.swing.JButton();
        btn_consultarClientes = new javax.swing.JButton();
        btn_consultarInventario = new javax.swing.JButton();

        btn_inicioSesión.setBackground(new java.awt.Color(68, 66, 110));
        btn_inicioSesión.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_inicioSesión.setForeground(new java.awt.Color(255, 255, 255));
        btn_inicioSesión.setText("Iniciar Sesión");
        btn_inicioSesión.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 38, 67));

        lbl_Activaciones.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbl_Activaciones.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Activaciones.setText("Activaciones Los Amigos");

        lbl_bienvenida.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bienvenida.setText("Bienvenido ");

        btn_registrarVentas.setBackground(new java.awt.Color(68, 66, 110));
        btn_registrarVentas.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_registrarVentas.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarVentas.setText("Registrar Ventas");
        btn_registrarVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_registrarVentas.setMaximumSize(new java.awt.Dimension(171, 27));
        btn_registrarVentas.setMinimumSize(new java.awt.Dimension(171, 27));
        btn_registrarVentas.setPreferredSize(new java.awt.Dimension(171, 27));
        btn_registrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarVentasActionPerformed(evt);
            }
        });

        btn_cerrarSesion.setBackground(new java.awt.Color(201, 101, 0));
        btn_cerrarSesion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrarSesion.setText("Cerrar Sesión");
        btn_cerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_cerrarSesion.setMaximumSize(new java.awt.Dimension(171, 27));
        btn_cerrarSesion.setMinimumSize(new java.awt.Dimension(171, 27));
        btn_cerrarSesion.setPreferredSize(new java.awt.Dimension(171, 27));
        btn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarSesionActionPerformed(evt);
            }
        });

        btn_consultarClientes.setBackground(new java.awt.Color(68, 66, 110));
        btn_consultarClientes.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_consultarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultarClientes.setText("Consultar Clientes");
        btn_consultarClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_consultarClientes.setMaximumSize(new java.awt.Dimension(171, 27));
        btn_consultarClientes.setMinimumSize(new java.awt.Dimension(171, 27));
        btn_consultarClientes.setPreferredSize(new java.awt.Dimension(171, 27));
        btn_consultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarClientesActionPerformed(evt);
            }
        });

        btn_consultarInventario.setBackground(new java.awt.Color(68, 66, 110));
        btn_consultarInventario.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_consultarInventario.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultarInventario.setText("Consultar Inventario");
        btn_consultarInventario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_consultarInventario.setMaximumSize(new java.awt.Dimension(171, 27));
        btn_consultarInventario.setMinimumSize(new java.awt.Dimension(171, 27));
        btn_consultarInventario.setPreferredSize(new java.awt.Dimension(171, 27));
        btn_consultarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lbl_Activaciones)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_registrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_bienvenida)
                        .addGap(263, 263, 263))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_Activaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bienvenida)
                .addGap(37, 37, 37)
                .addComponent(btn_registrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_consultarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btn_consultarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarVentasActionPerformed
        IniciarVenta form = new IniciarVenta();
        form.setVisible(true);
    }//GEN-LAST:event_btn_registrarVentasActionPerformed

    private void btn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarSesionActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarSesionActionPerformed

    private void btn_consultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarClientesActionPerformed
        EmpleadoCliente form = new EmpleadoCliente();
        form.setVisible(true);
    }//GEN-LAST:event_btn_consultarClientesActionPerformed

    private void btn_consultarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarInventarioActionPerformed
        EmpleadoInventario form = new EmpleadoInventario();
        form.setVisible(true);
    }//GEN-LAST:event_btn_consultarInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipalEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrarSesion;
    private javax.swing.JButton btn_consultarClientes;
    private javax.swing.JButton btn_consultarInventario;
    private javax.swing.JButton btn_inicioSesión;
    private javax.swing.JButton btn_registrarVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Activaciones;
    private javax.swing.JLabel lbl_bienvenida;
    // End of variables declaration//GEN-END:variables
}
